name: an announcement action that takes the app name
on: push
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: checking out the code
        uses: actions/checkout@v4
      - name: using composite actions
        uses: ./.github/actions/announce
        with:
          app-name: pixelpost
