name: site-check
on: push
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: checking out the code
        uses: actions/checkout@v4
      - name: Read the readme
        run: cat README.md
      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Show the Python version
        run: python --version
