name: B reusable workflow that takes an input and a secret
on: push
jobs:
  caller:
    uses: ./.github/workflows/notify.yml
    with:
      environment: gowrishankar
    secrets:
      NOTIFY_TOKEN: ${{ secrets. NOTIFY_TOKEN }}
